// <auto-generated />
using System;
using Casino.DataAccess.MenuVoting.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Casino.DataAccess.Migrations
{
    [DbContext(typeof(CasinoDbContext))]
    [Migration("20241213192001_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Casino.DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("52fdf31c-27c4-498b-bad3-d56394b8d51d"),
                            Email = "john@gmail.com",
                            FirstName = "John",
                            LastName = "Robinson",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("1109a562-aa69-4d01-8eba-10175eeaad5c"),
                            Email = "bremer@gmail.com",
                            FirstName = "Mark",
                            LastName = "Bremer",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("74757949-c32b-44ea-a7d0-0bf457b8a90e"),
                            Email = "jackrich@gmail.com",
                            FirstName = "Jack",
                            LastName = "Richardson",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = new Guid("8fc92e40-f91f-40bf-89ff-5e68578d4367"),
                            Email = "joseph@gmail.com",
                            FirstName = "Joseph",
                            LastName = "Borr",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("074cdd40-be99-456d-9740-791abd93024f"),
                            Email = "bart@gmail.com",
                            FirstName = "Max",
                            LastName = "Bart",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = new Guid("df44d370-e174-4426-a52e-58a260f704eb"),
                            Email = "spencer@gmail.com",
                            FirstName = "Nicholas",
                            LastName = "Spencer",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("6d6b0494-edb0-439c-9fef-7d4bb5cb71f3"),
                            Email = "eugene@gmail.com",
                            FirstName = "Eugene",
                            LastName = "Lagelle",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = new Guid("3ed704f4-40aa-42e2-8119-a6c6daaba0a6"),
                            Email = "thudor@gmail.com",
                            FirstName = "Richard",
                            LastName = "Thudor",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("d7e63a43-a93b-42ed-aa8f-727c75e53cda"),
                            Email = "bock@gmail.com",
                            FirstName = "Andrew",
                            LastName = "Bock",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = new Guid("d46defd8-526b-4d86-b903-412f59673b2d"),
                            Email = "bluementhal@gmail.com",
                            FirstName = "George",
                            LastName = "Bluementhal",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("95da71d2-830b-4da6-8c35-55a96aa2487e"),
                            Email = "smithm@gmail.com",
                            FirstName = "Marry",
                            LastName = "Smith",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = new Guid("8558b449-4562-4234-a78f-2996681bff6a"),
                            Email = "rudhampspring@gmail.com",
                            FirstName = "Rudolf",
                            LastName = "Hampspring",
                            PhoneNumber = "1234567890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
